# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'viewer.ui'
#
# Created by: PyQt5 UI code generator 5.15.10
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(1345, 719)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.horizontalLayoutWidget = QtWidgets.QWidget(self.centralwidget)
        self.horizontalLayoutWidget.setGeometry(QtCore.QRect(-10, 0, 1341, 32))
        self.horizontalLayoutWidget.setObjectName("horizontalLayoutWidget")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.horizontalLayoutWidget)
        self.horizontalLayout.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.pushButton = QtWidgets.QPushButton(self.horizontalLayoutWidget)
        self.pushButton.setObjectName("pushButton")
        self.horizontalLayout.addWidget(self.pushButton)
        self.pushButton_Add = QtWidgets.QPushButton(self.horizontalLayoutWidget)
        self.pushButton_Add.setObjectName("pushButton_Add")
        self.horizontalLayout.addWidget(self.pushButton_Add)
        self.pushButton_delete = QtWidgets.QPushButton(self.horizontalLayoutWidget)
        self.pushButton_delete.setObjectName("pushButton_delete")
        self.horizontalLayout.addWidget(self.pushButton_delete)
        MainWindow.setCentralWidget(self.centralwidget)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)
        self.menuBar = QtWidgets.QMenuBar(MainWindow)
        self.menuBar.setGeometry(QtCore.QRect(0, 0, 1345, 24))
        self.menuBar.setObjectName("menuBar")
        self.menuFolder = QtWidgets.QMenu(self.menuBar)
        self.menuFolder.setObjectName("menuFolder")
        self.menuSettings = QtWidgets.QMenu(self.menuBar)
        self.menuSettings.setObjectName("menuSettings")
        MainWindow.setMenuBar(self.menuBar)
        self.actionAdd = QtWidgets.QAction(MainWindow)
        self.actionAdd.setObjectName("actionAdd")
        self.actionOpen = QtWidgets.QAction(MainWindow)
        self.actionOpen.setObjectName("actionOpen")
        self.actionAdd_2 = QtWidgets.QAction(MainWindow)
        self.actionAdd_2.setObjectName("actionAdd_2")
        self.actionDlete = QtWidgets.QAction(MainWindow)
        self.actionDlete.setObjectName("actionDlete")
        self.actionLoadAllSubFolders = QtWidgets.QAction(MainWindow)
        self.actionLoadAllSubFolders.setObjectName("actionLoadAllSubFolders")
        self.action_Add_1_Folder = QtWidgets.QAction(MainWindow)
        self.action_Add_1_Folder.setObjectName("action_Add_1_Folder")
        self.action_Delete_the_last_Folder = QtWidgets.QAction(MainWindow)
        self.action_Delete_the_last_Folder.setObjectName("action_Delete_the_last_Folder")
        self.actionConfigs = QtWidgets.QAction(MainWindow)
        self.actionConfigs.setObjectName("actionConfigs")
        self.menuFolder.addAction(self.actionLoadAllSubFolders)
        self.menuFolder.addSeparator()
        self.menuFolder.addAction(self.action_Add_1_Folder)
        self.menuFolder.addAction(self.action_Delete_the_last_Folder)
        self.menuFolder.addSeparator()
        self.menuSettings.addAction(self.actionConfigs)
        self.menuBar.addAction(self.menuFolder.menuAction())
        self.menuBar.addAction(self.menuSettings.menuAction())

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.pushButton.setText(_translate("MainWindow", "Load All from a Parent Folder"))
        self.pushButton_Add.setText(_translate("MainWindow", "+ Add 1 Folder"))
        self.pushButton_delete.setText(_translate("MainWindow", "- Delete the last 1 Folder"))
        self.menuFolder.setTitle(_translate("MainWindow", "Folder"))
        self.menuSettings.setTitle(_translate("MainWindow", "Settings"))
        self.actionAdd.setText(_translate("MainWindow", "Add"))
        self.actionOpen.setText(_translate("MainWindow", "Open"))
        self.actionAdd_2.setText(_translate("MainWindow", "+Add"))
        self.actionDlete.setText(_translate("MainWindow", "-Delete"))
        self.actionLoadAllSubFolders.setText(_translate("MainWindow", "LoadAllSubFolders"))
        self.action_Add_1_Folder.setText(_translate("MainWindow", "+Add 1 Folder"))
        self.action_Delete_the_last_Folder.setText(_translate("MainWindow", "-Delete 1 Folder"))
        self.actionConfigs.setText(_translate("MainWindow", "Configs"))
