# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'viewer.ui'
#
# Created by: PyQt5 UI code generator 5.15.10
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        self.MainWindow = MainWindow
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(1268, 719)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.gridLayoutWidget = QtWidgets.QWidget(self.centralwidget)
        self.gridLayoutWidget.setGeometry(QtCore.QRect(9, 39, 1251, 631))
        self.gridLayoutWidget.setObjectName("gridLayoutWidget")
        self.gridLayout = QtWidgets.QGridLayout(self.gridLayoutWidget)
        self.gridLayout.setContentsMargins(0, 0, 0, 0)
        self.gridLayout.setObjectName("gridLayout")
        # self.pushButton_zoom = QtWidgets.QPushButton(self.centralwidget)
        # self.pushButton_zoom.setGeometry(QtCore.QRect(1110, 0, 113, 32))
        # self.pushButton_zoom.setObjectName("pushButton_zoom")
        self.pushButton_Add = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_Add.setGeometry(QtCore.QRect(30, 0, 113, 32))
        self.pushButton_Add.setObjectName("pushButton_Add")
        self.pushButton_delete = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_delete.setGeometry(QtCore.QRect(150, 0, 113, 32))
        self.pushButton_delete.setObjectName("pushButton_delete")
        MainWindow.setCentralWidget(self.centralwidget)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)
        # self.menubar = QtWidgets.QMenuBar(MainWindow)
        # self.menubar.setGeometry(QtCore.QRect(0, 0, 1268, 24))
        # self.menubar.setObjectName("menubar")
        # self.menuFolder = QtWidgets.QMenu(self.menubar)
        # self.menuFolder.setObjectName("menuFolder")
        # self.menuGrid = QtWidgets.QMenu(self.menubar)
        # self.menuGrid.setObjectName("menuGrid")
        # MainWindow.setMenuBar(self.menubar)
        self.actionAdd = QtWidgets.QAction(MainWindow)
        self.actionAdd.setObjectName("actionAdd")
        self.actionOpen = QtWidgets.QAction(MainWindow)
        self.actionOpen.setObjectName("actionOpen")
        self.actionAdd_2 = QtWidgets.QAction(MainWindow)
        self.actionAdd_2.setObjectName("actionAdd_2")
        self.actionDlete = QtWidgets.QAction(MainWindow)
        self.actionDlete.setObjectName("actionDlete")
        # self.menuFolder.addAction(self.actionOpen)
        # self.menuGrid.addAction(self.actionAdd_2)
        # self.menuGrid.addAction(self.actionDlete)
        # self.menubar.addAction(self.menuFolder.menuAction())
        # self.menubar.addAction(self.menuGrid.menuAction())

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)
    
    def keyPressEvent(self, event):
        self.MainWindow.keyPressEvent(event)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        # self.pushButton_zoom.setText(_translate("MainWindow", "Zoom"))
        self.pushButton_Add.setText(_translate("MainWindow", "+Add Folder"))
        self.pushButton_delete.setText(_translate("MainWindow", "-Delete Folder"))
        # self.menuFolder.setTitle(_translate("MainWindow", "Folder"))
        # self.menuGrid.setTitle(_translate("MainWindow", "Grid"))
        self.actionAdd.setText(_translate("MainWindow", "Add"))
        self.actionOpen.setText(_translate("MainWindow", "Open"))
        self.actionAdd_2.setText(_translate("MainWindow", "+Add"))
        self.actionDlete.setText(_translate("MainWindow", "-Delete"))
