# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'ui/base.ui'
#
# Created by: PyQt5 UI code generator 5.15.10
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Base(object):
    def setupUi(self, Base):
        Base.setObjectName("Base")
        Base.resize(1378, 701)
        self.centralwidget = QtWidgets.QWidget(Base)
        self.centralwidget.setObjectName("centralwidget")
        Base.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(Base)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 1378, 24))
        self.menubar.setObjectName("menubar")
        self.menuFile = QtWidgets.QMenu(self.menubar)
        self.menuFile.setObjectName("menuFile")
        self.menuConfigs = QtWidgets.QMenu(self.menubar)
        self.menuConfigs.setObjectName("menuConfigs")
        self.menuAction = QtWidgets.QMenu(self.menubar)
        self.menuAction.setObjectName("menuAction")
        Base.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(Base)
        self.statusbar.setObjectName("statusbar")
        Base.setStatusBar(self.statusbar)
        self.actionLoadSubFolders = QtWidgets.QAction(Base)
        self.actionLoadSubFolders.setObjectName("actionLoadSubFolders")
        self.actionAdd1Folder = QtWidgets.QAction(Base)
        self.actionAdd1Folder.setObjectName("actionAdd1Folder")
        self.actionDel1Folder = QtWidgets.QAction(Base)
        self.actionDel1Folder.setObjectName("actionDel1Folder")
        self.actionSave = QtWidgets.QAction(Base)
        self.actionSave.setObjectName("actionSave")
        self.actionGoTo = QtWidgets.QAction(Base)
        self.actionGoTo.setObjectName("actionGoTo")
        self.actionGoToName = QtWidgets.QAction(Base)
        self.actionGoToName.setObjectName("actionGoToName")
        self.actionOpenRemote = QtWidgets.QAction(Base)
        self.actionOpenRemote.setObjectName("actionOpenRemote")
        self.actionConfigSSH = QtWidgets.QAction(Base)
        self.actionConfigSSH.setObjectName("actionConfigSSH")
        self.actionConfigWindow = QtWidgets.QAction(Base)
        self.actionConfigWindow.setObjectName("actionConfigWindow")
        self.actionConnect = QtWidgets.QAction(Base)
        self.actionConnect.setObjectName("actionConnect")
        self.actionSaveCrop = QtWidgets.QAction(Base)
        self.actionSaveCrop.setObjectName("actionSaveCrop")
        self.menuFile.addAction(self.actionLoadSubFolders)
        self.menuFile.addAction(self.actionAdd1Folder)
        self.menuFile.addAction(self.actionDel1Folder)
        self.menuFile.addSeparator()
        self.menuFile.addAction(self.actionSave)
        self.menuFile.addAction(self.actionSaveCrop)
        self.menuFile.addSeparator()
        self.menuFile.addAction(self.actionOpenRemote)
        self.menuConfigs.addAction(self.actionConfigWindow)
        self.menuAction.addAction(self.actionGoTo)
        self.menuAction.addAction(self.actionGoToName)
        self.menuAction.addSeparator()
        self.menubar.addAction(self.menuFile.menuAction())
        self.menubar.addAction(self.menuAction.menuAction())
        self.menubar.addAction(self.menuConfigs.menuAction())

        self.retranslateUi(Base)
        QtCore.QMetaObject.connectSlotsByName(Base)

    def retranslateUi(self, Base):
        _translate = QtCore.QCoreApplication.translate
        Base.setWindowTitle(_translate("Base", "MainWindow"))
        self.menuFile.setTitle(_translate("Base", "File"))
        self.menuConfigs.setTitle(_translate("Base", "Configs"))
        self.menuAction.setTitle(_translate("Base", "Action"))
        self.actionLoadSubFolders.setText(_translate("Base", "Load all..."))
        self.actionAdd1Folder.setText(_translate("Base", "+ Add 1 folder"))
        self.actionDel1Folder.setText(_translate("Base", "- Del 1 folder"))
        self.actionSave.setText(_translate("Base", "Save..."))
        self.actionGoTo.setText(_translate("Base", "GoTo Index"))
        self.actionGoToName.setText(_translate("Base", "GoTo Name"))
        self.actionOpenRemote.setText(_translate("Base", "Open remote"))
        self.actionConfigSSH.setText(_translate("Base", "SSH"))
        self.actionConfigWindow.setText(_translate("Base", "Window"))
        self.actionConnect.setText(_translate("Base", "connect"))
        self.actionSaveCrop.setText(_translate("Base", "Save crop..."))
