# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'goto.ui'
#
# Created by: PyQt5 UI code generator 5.15.7
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Dialog(object):
    def setupUi(self, Dialog, title='Dialog', label='input', edit='line'):
        margin = 30
        border = 10
        button_height = 30
        edit_w = 123

        Dialog.setObjectName("Dialog") 
        self.buttonBox = QtWidgets.QDialogButtonBox(Dialog)
        self.buttonBox.setOrientation(QtCore.Qt.Horizontal)
        self.buttonBox.setStandardButtons(QtWidgets.QDialogButtonBox.Cancel|QtWidgets.QDialogButtonBox.Ok)
        self.buttonBox.setObjectName("buttonBox")

        self.label = QtWidgets.QLabel(Dialog)
        self.label.setObjectName("label")
        self.retranslateUi(Dialog, label, title)

        # label_str_len = len(label) * (30 // len('input'))
        label_str_len = QtGui.QFontMetrics(self.label.font()).width(label) + border
        print(len(label), label_str_len)
        if edit == 'line':
            # line Edit
            edit_h = 21
            self.editor = QtWidgets.QLineEdit(Dialog)
            self.editor.setGeometry(QtCore.QRect(margin+label_str_len, margin, edit_w, edit_h))
            self.editor.setObjectName("lineEdit")
        elif edit == 'text':
            # text Edit
            edit_h = 100
            self.editor = QtWidgets.QTextEdit(Dialog)
            self.editor.setGeometry(QtCore.QRect(margin+label_str_len, margin, edit_w, edit_h))
            self.editor.setPlaceholderText("Enter your text here...")
        else:
            raise NotImplementedError(f'edit type {edit} not implemented')
        
        space = 2*margin + border
        Dialog.resize(space+edit_w+label_str_len, space+button_height+edit_h)
        self.label.setGeometry(QtCore.QRect(margin, margin, label_str_len, 16))
        self.buttonBox.setGeometry(
            QtCore.QRect(margin, margin+edit_h+border, edit_w+label_str_len+border, 32))

        self.buttonBox.accepted.connect(Dialog.accept) # type: ignore
        self.buttonBox.rejected.connect(Dialog.reject) # type: ignore
        QtCore.QMetaObject.connectSlotsByName(Dialog)

    def retranslateUi(self, Dialog, label, title):
        _translate = QtCore.QCoreApplication.translate
        Dialog.setWindowTitle(_translate("Dialog", title))
        self.label.setText(_translate("Dialog", label))
